DROP TABLE IF EXISTS safv.cliente;
CREATE TABLE safv.cliente (
  agencia varchar(3)  ,
  codigo varchar(20) NOT NULL ,
  nombre char(100)  ,
  cedula varchar(14) NOT NULL ,
  nrorif varchar(25) ,
  direccion varchar(200) ,
  telefonos varchar(150) ,
  telefono_movil varchar(150) ,
  numerofax varchar(150) ,
  status double(2,0)  ,
  nota longtext,
  email varchar(1024) ,
  vendedor varchar(8) ,
  tipo varchar(10) ,
  direccobro longtext,
  direcenvio longtext,
  sexo double(2,0)  ,
  nacionalidad varchar(20) ,
  fechanac date  ,
  edocivil double(2,0)  ,
  telhabitacion varchar(60) ,
  celular varchar(40) ,
  mediovisto varchar(30) ,
  sucursal varchar(15) ,
  contribespecial double(4,0)  ,
  tipopersona double(4,0)  ,
  codban_beneficiario varchar(3) ,
  codban_intermediario varchar(3) ,
  nombre_beneficiario varchar(60) ,
  cuenta_beneficiario varchar(60) ,
  tipo_cuenta_beneficiario varchar(25) ,
  PRIMARY KEY (codigo,cedula),
  UNIQUE KEY codigo (codigo)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='innodb free: 7168 kb';
