DROP TABLE IF EXISTS safv.orden;
CREATE TABLE safv.orden (
  agencia varchar(3)NOT NULL ,
  moneda varchar(3) ,
  tipodoc varchar(3) NOT NULL,
  documento varchar(8) NOT NULL,
  codcliente varchar(20) NOT NULL,
  fechaemi date NOT NULL ,  
  nombrecli varchar(100) ,
  contacto varchar(50) ,
  rif varchar(25) ,
  direccion varchar(200) ,
  telefonos varchar(50) ,
  emision date ,
  vence date ,
  fechacrea date ,
  totalfinal double(24,7) ,
  totimpuest double(24,7) ,
  totdescuen double(24,7) ,
  impuesto1 double(24,7) ,
  recargos double(24,7) ,
  dsctoend1 double(24,7) ,
  notas longtext,
  estatusdoc varchar(1) ,
  ultimopag date ,
  vendedor varchar(8) ,
  factorcamb double(24,12) ,
  uemisor varchar(30) ,
  almacen varchar(2) ,
  sector varchar(6) ,
  codigoret varchar(3) ,
  retencion double(24,7) ,
  aplicadoa varchar(11) ,
  horadocum varchar(5) ,
  procedecre double(4,0) ,
  entregado double(2,0) ,
  vuelto double(24,7) ,
  seq_nodo varchar(10) ,
  chequedev double(4,0) ,
  baseimpo1 double(24,7) ,
  iddocumento varchar(8) ,
  imp_nacional double(24,7) ,
  retencioniva double(20,7) ,
  fechayhora datetime NOT NULL ,
  tipopersona double(4,0) ,
  usa_despacho double(4,0) ,
  despachador varchar(15) ,
  despacho_nro varchar(8) ,
  PRIMARY KEY operti_ppal (agencia,tipodoc,documento,codcliente,fechaemi),
  KEY operti_tipodoc_idx (documento),
  KEY codcliente (codcliente)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='innodb free: 7168 kb';
